name: Build Linux x64

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build-linux-x64:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y fuse libfuse2
          dotnet tool install -g KuiperZone.PupNet
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
          cd $GITHUB_WORKSPACE
          curl -sL https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage -o appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          echo "$GITHUB_WORKSPACE" >> $GITHUB_PATH

      - name: Clean & Restore
        run: |
          cd PCL.Neo
          dotnet clean
          rm -rf bin obj Deploy
          dotnet restore

      - name: Build AppImage
        run: |
          cd PCL.Neo
          pupnet --runtime linux-x64 --kind appimage -o PCL.Neo.linux.x64.AppImage -y --app-version 1.0.0

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: PCL.Neo/Deploy/OUT/PCL.Neo.linux.x64.AppImage
